### ISSUE TITLE
after new mobile device registration, parse keeps on sending push notification to old device

### ISSUE THREAD

**Issue by josjevv** [bulletind/khabar#85]
after working around by deleting notifications user gully settings (see #84), device registration on khabar seems successful. However, push notification is still received on previously registered device.

settings used:
data: {
   parse_application_id: "*****",
   parse_installation_id: "*****",
   parse_rest_api_key: "*****"
 },

**Comment by meson10** [comment]
If you subscribe to the User channel appropriately, you would receive notifications on all of them.
And device registrations are not supposed to work "only 1 at a time" a user can have multiple devices.

**Comment by josjevv** [comment]
if this would work the way you describe, we would not be having this problem.

**Comment by meson10** [comment]
Error at mobile end?

**Comment by meson10** [comment]
I hope, github does not version control the issues :)

**Comment by josjevv** [comment]
Ok, it seems like the installation_id is not being used at all, but a channel is used. The issue turned out to be a mismatching SSL Push Notification Certificate
